url: https://giaiphapso.io.vn
baseurl: ""

# Site settings
title: giaiphapso
email: tranquangthanhcong@gmail.com
description: "Chúng tôi cung cấp giải pháp quản lý doanh nghiệp nhỏ bằng công nghệ, giúp doanh nghiệp hoạt động hiệu quả hơn đồng thời tiết kiệm thời gian, công sức và chi phí."


# Team names, titles and social links
people:
- name: Công Trần
  pic: congtran
  position: Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty